// Generated by Discovery.ts -- do not edit by hand.
// Action: manage recipients (add, remove, or update recipient information)
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-21T21:35:42.901Z

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';
import type { RecipeOutcome } from '../recipeRuntime.ts';

export const TASK = "manage recipients (add, remove, or update recipient information)";
export const ACTION = "manage recipients (add, remove, or update recipient information)";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown>; onHardFailure?: (info: { message: string; step?: string; expected?: string; observed?: string }, closeBrowser: () => Promise<void>) => Promise<void> } = {}): Promise<RecipeOutcome> {
    const rawOperation = context.parameters?.operation;
    if (rawOperation === undefined || rawOperation === null || String(rawOperation).trim() === "") {
        throw new Error("Missing required parameter: operation");
    }
    const operation = String(rawOperation);

    const rawRecipientName = context.parameters?.recipientName;
    if (rawRecipientName === undefined || rawRecipientName === null) {
        throw new Error("Missing required parameter: recipientName");
    }
    const recipientNames: string[] = (Array.isArray(rawRecipientName) ? rawRecipientName : [rawRecipientName])
        .map((entry) => {
            if (entry === undefined || entry === null || String(entry).trim() === "") {
                throw new Error("Invalid value in parameter: recipientName");
            }
            return String(entry);
        });
    if (recipientNames.length === 0) {
        throw new Error("Missing required parameter: recipientName");
    }

    return runRecipe(async (page, out) => {
        await recipeGoto(page, "https://www.ngpf.org/bank-sim/");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"GET STARTED NOW"},{"kind":"within","anchorText":"NGPF Bank Simulator","ancestor":"mat-card","css":"button.button.mat-raised-button"},{"kind":"text","value":"GET STARTED NOW"}], "button \"GET STARTED NOW\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Ok"},{"kind":"text","value":"Ok"}], "button \"Ok\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"TRANSFERS expand_more"}], "link \"TRANSFERS expand_more\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ONLINE SERVICES"}], "link \"ONLINE SERVICES\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"MAKE A TRANSFER"}], "link \"MAKE A TRANSFER\"");
        await settle(page);
        await recipeClick(page, [{"kind":"label","value":"Transfer To *"},{"kind":"css","value":"#mat-select-4"}], "combobox \"\"");
        await settle(page);
        await recipePress(page, "Escape");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"BILLS expand_more"}], "link \"BILLS expand_more\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"MANAGE RECIPIENT"}], "link \"MANAGE RECIPIENT\"");
        await settle(page);
        for (const recipientName of recipientNames) {
            await recipeClick(page, [{"kind":"text","value":"ADD RECIPIENT"}], "span \"ADD RECIPIENT\"");
            await settle(page);
            await recipeFill(page, [{"kind":"label","value":"RECIPIENT NAME *"},{"kind":"placeholder","value":"Enter name"},{"kind":"css","value":"#mat-input-3"}], "textbox \"\"", recipientName);
            await settle(page);
        }
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
        onHardFailure: context.onHardFailure,
    });
}