// Generated by Discovery.ts -- do not edit by hand.
// Action: retrieve account activity information (purchases, deposits, deductions)
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-21T21:48:07.594Z

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';
import type { RecipeOutcome } from '../recipeRuntime.ts';

export const TASK = "retrieve account activity information (purchases, deposits, deductions)";
export const ACTION = "retrieve account activity information (purchases, deposits, deductions)";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown>; onHardFailure?: (info: { message: string; step?: string; expected?: string; observed?: string }, closeBrowser: () => Promise<void>) => Promise<void> } = {}): Promise<RecipeOutcome> {
    const rawActivityType = context.parameters?.activityType;
    if (rawActivityType === undefined || rawActivityType === null || String(rawActivityType).trim() === "") {
        throw new Error("Missing required parameter: activityType");
    }
    const activityType = String(rawActivityType).trim();

    const rawFilter = context.parameters?.filter;
    if (rawFilter === undefined || rawFilter === null || String(rawFilter).trim() === "") {
        throw new Error("Missing required parameter: filter");
    }
    const filter = String(rawFilter).trim();

    const singularActivityType = activityType.endsWith("s") ? activityType.slice(0, -1) : activityType;
    const amountKey = `${filter}_${singularActivityType}_amount`;
    const merchantKey = `${filter}_${singularActivityType}_merchant`;

    return runRecipe(async (page, out) => {
        await recipeGoto(page, "https://www.ngpf.org/bank-sim/");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"GET STARTED NOW"},{"kind":"within","anchorText":"NGPF Bank Simulator","ancestor":"mat-card","css":"button.button.mat-raised-button"},{"kind":"text","value":"GET STARTED NOW"}], "button \"GET STARTED NOW\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Ok"},{"kind":"text","value":"Ok"}], "button \"Ok\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNTS expand_more"}], "link \"ACCOUNTS expand_more\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNT ACTIVITY"}], "link \"ACCOUNT ACTIVITY\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Saving"},{"kind":"text","value":"Saving"}], "button \"Saving\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Checking"},{"kind":"text","value":"Checking"}], "button \"Checking\"");
        await settle(page);
        out[amountKey] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"-$18.99"},{"kind":"text","value":"-$18.99"}], "cell \"-$18.99\"")).trim();
        out[merchantKey] = (await recipeExtract(page, [{"kind":"text","value":"Cool Clothes Co"}], "span \"Cool Clothes Co\"")).trim();
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
        onHardFailure: context.onHardFailure,
    });
}