// Generated by Discovery.ts -- do not edit by hand.
// Task: retrieve bank account balance details
// Action: retrieve bank account balance details
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-20T19:16:22.727Z

import { recipeClick, recipeExtract, recipeGoto, runRecipe, settle } from '../recipeRuntime.ts';
import type { Selector } from '../recipeRuntime.ts';

export const TASK = "retrieve bank account balance details";
export const ACTION = "retrieve bank account balance details";
export const URL = "https://www.ngpf.org/bank-sim/";

interface AccountConfig {
    label: string;
    anchors: string[];
    outputKey: string;
}

const ACCOUNTS: AccountConfig[] = [
    {
        label: 'Savings',
        anchors: ['Saving Account Activity', 'Savings Account', 'SAVINGS'],
        outputKey: 'savings_balance',
    },
    {
        label: 'Checking',
        anchors: ['Checking Account Activity', 'Checking Account', 'CHECKING'],
        outputKey: 'checking_balance',
    },
];

function balanceSelectors(account: AccountConfig): Selector[] {
    return account.anchors.flatMap((anchor) => [
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: '.balance' },
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: 'div' },
        { kind: 'within', anchorText: anchor, ancestor: 'div', css: '.balance' },
    ]);
}

async function extractBalance(
    page: Parameters<typeof recipeGoto>[0],
    account: AccountConfig,
): Promise<string> {
    return recipeExtract(page, balanceSelectors(account), `${account.label} account balance`);
}

export async function runAction(
    context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown> } = {},
): Promise<Record<string, string>> {
    const targetUrl = context.inputUrl && context.inputUrl.trim().length > 0 ? context.inputUrl : URL;

    return runRecipe(async (page, out) => {
        await recipeGoto(page, targetUrl);
        await settle(page);
        await recipeClick(
            page,
            [
                { kind: 'role', role: 'button', name: 'GET STARTED NOW' },
                { kind: 'text', value: 'GET STARTED NOW' },
            ],
            'button "GET STARTED NOW"',
        );
        await settle(page);

        for (const account of ACCOUNTS) {
            out[account.outputKey] = (await extractBalance(page, account)).trim();
        }
    }, {
        headed: process.env.HEADED === '1',
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
    });
}
