// Generated by Discovery.ts -- do not edit by hand.
// Task: retrieve account activity information (purchases, deposits, deductions)
// Action: retrieve account activity information (purchases, deposits, deductions)
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-20T17:48:22.851Z

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';

export const TASK = "retrieve account activity information (purchases, deposits, deductions)";
export const ACTION = "retrieve account activity information (purchases, deposits, deductions)";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown> } = {}): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
        await recipeGoto(page, "https://www.ngpf.org/bank-sim/");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"GET STARTED NOW"},{"kind":"within","anchorText":"NGPF Bank Simulator","ancestor":"mat-card","css":"button.button.mat-raised-button"},{"kind":"text","value":"GET STARTED NOW"}], "button \"GET STARTED NOW\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Ok"},{"kind":"text","value":"Ok"}], "button \"Ok\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNTS expand_more"}], "link \"ACCOUNTS expand_more\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNT ACTIVITY"}], "link \"ACCOUNT ACTIVITY\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Saving"},{"kind":"text","value":"Saving"}], "button \"Saving\"");
        await settle(page);
        out["savings_activity"] = (await recipeExtract(page, [{"kind":"within","anchorText":"Account Activity","ancestor":"mat-card","css":"h2"},{"kind":"text","value":"Account Activity"}], "h2 \"Account Activity\"")).trim();
        out["savings_txn1_desc"] = (await recipeExtract(page, [{"kind":"text","value":"Network ATM"}], "span \"Network ATM\"")).trim();
        out["savings_txn2_desc"] = (await recipeExtract(page, [{"kind":"text","value":"Account Opening"}], "span \"Account Opening\"")).trim();
        out["savings_txn1_amount"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"-$20.00"},{"kind":"text","value":"-$20.00"}], "cell \"-$20.00\"")).trim();
        out["savings_balance"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"$230.00"},{"kind":"text","value":"$230.00"}], "cell \"$230.00\"")).trim();
        await recipeClick(page, [{"kind":"role","role":"button","name":"Checking"},{"kind":"text","value":"Checking"}], "button \"Checking\"");
        await settle(page);
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
    });
}
