// Generated by Discovery.ts -- do not edit by hand.
// Action: retrieve account activity information (purchases, deposits, deductions)
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-21T19:02:32.047Z

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';
import type { RecipeOutcome } from '../recipeRuntime.ts';

export const TASK = "retrieve account activity information (purchases, deposits, deductions)";
export const ACTION = "retrieve account activity information (purchases, deposits, deductions)";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown>; onHardFailure?: (info: { message: string; step?: string; expected?: string; observed?: string }, closeBrowser: () => Promise<void>) => Promise<void> } = {}): Promise<RecipeOutcome> {
    return runRecipe(async (page, out) => {
        await recipeGoto(page, "https://www.ngpf.org/bank-sim/");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"GET STARTED NOW"},{"kind":"within","anchorText":"NGPF Bank Simulator","ancestor":"mat-card","css":"button.button.mat-raised-button"},{"kind":"text","value":"GET STARTED NOW"}], "button \"GET STARTED NOW\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Ok"},{"kind":"text","value":"Ok"}], "button \"Ok\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNTS expand_more"}], "link \"ACCOUNTS expand_more\"");
        await settle(page);
        await recipeClick(page, [{"kind":"text","value":"ACCOUNT ACTIVITY"}], "link \"ACCOUNT ACTIVITY\"");
        await settle(page);
        out["checking_activity_section"] = (await recipeExtract(page, [{"kind":"within","anchorText":"Account Activity","ancestor":"mat-card","css":"h2"},{"kind":"text","value":"Account Activity"}], "h2 \"Account Activity\"")).trim();
        out["checking_txn1_amount_streamwave_09_20"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"-$6.99"},{"kind":"text","value":"-$6.99"}], "cell \"-$6.99\"")).trim();
        out["checking_txn4_amount_coolclothes_09_16"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"-$18.99"},{"kind":"text","value":"-$18.99"}], "cell \"-$18.99\"")).trim();
        out["checking_current_balance"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"$216.04"},{"kind":"text","value":"$216.04"}], "cell \"$216.04\"")).trim();
        await recipeClick(page, [{"kind":"role","role":"button","name":"Saving"},{"kind":"text","value":"Saving"}], "button \"Saving\"");
        await settle(page);
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
        onHardFailure: context.onHardFailure,
    });
}
