// Generated by Discovery.ts -- do not edit by hand.
// Task: retrieve bills information
// Action: retrieve bills information
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-20T17:38:20.676Z

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';

export const TASK = "retrieve bills information";
export const ACTION = "retrieve bills information";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown> } = {}): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
        await recipeGoto(page, "https://www.ngpf.org/bank-sim/");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"GET STARTED NOW"},{"kind":"within","anchorText":"NGPF Bank Simulator","ancestor":"mat-card","css":"button.button.mat-raised-button"},{"kind":"text","value":"GET STARTED NOW"}], "button \"GET STARTED NOW\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"Ok"},{"kind":"text","value":"Ok"}], "button \"Ok\"");
        await settle(page);
        await recipeClick(page, [{"kind":"role","role":"button","name":"VIEW BILLS"},{"kind":"text","value":"VIEW BILLS"}], "button \"VIEW BILLS\"");
        await settle(page);
        out["upcoming_bill_id"] = (await recipeExtract(page, [{"kind":"text","value":"1200005"}], "span \"1200005\"")).trim();
        out["upcoming_bill_date"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"10/19/2026"},{"kind":"text","value":"10/19/2026"}], "cell \"10/19/2026\"")).trim();
        out["past_bill_id"] = (await recipeExtract(page, [{"kind":"text","value":"1200004"}], "span \"1200004\"")).trim();
        out["past_bill_date"] = (await recipeExtract(page, [{"kind":"role","role":"cell","name":"09/19/2026"},{"kind":"text","value":"09/19/2026"}], "cell \"09/19/2026\"")).trim();
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
    });
}
