// Generated by Discovery.ts -- do not edit by hand.
// Action: retrieve bank account balance details
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-21T19:01:03.765Z

import { recipeCheckpoint, recipeClick, recipeExtract, recipeGoto, runRecipe, settle } from '../recipeRuntime.ts';
import { businessOutcome } from '../recipeRuntime.ts';
import type { RecipeOutcome, Selector } from '../recipeRuntime.ts';

export const TASK = "retrieve bank account balance details";
export const ACTION = "retrieve bank account balance details";
export const URL = "https://www.ngpf.org/bank-sim/";

interface AccountConfig {
    label: string;
    anchors: string[];
    outputKey: string;
}

const ACCOUNTS: AccountConfig[] = [
    {
        label: 'Savings',
        anchors: ['Saving Account Activity', 'Savings Account', 'SAVINGS'],
        outputKey: 'savings_balance',
    },
    {
        label: 'Checking',
        anchors: ['Checking Account Activity', 'Checking Account', 'CHECKING'],
        outputKey: 'checking_balance',
    },
];

function balanceSelectors(account: AccountConfig): Selector[] {
    return account.anchors.flatMap((anchor) => [
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: '.balance' },
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: 'div' },
        { kind: 'within', anchorText: anchor, ancestor: 'div', css: '.balance' },
    ]);
}

async function extractBalance(
    page: Parameters<typeof recipeGoto>[0],
    account: AccountConfig,
): Promise<string> {
    return recipeExtract(page, balanceSelectors(account), `${account.label} account balance`);
}

/**
 * If the caller asked for a specific account type, requesting something
 * this recipe doesn't know how to look up (e.g. "credit card") is a
 * legitimate business outcome, not a crash: the recipe genuinely has no
 * way to answer that question, distinct from a runtime failure.
 */
function requestedAccounts(parameters: Record<string, unknown> | undefined): AccountConfig[] {
    const requested = parameters?.accountType ?? parameters?.account ?? parameters?.accountScope;
    if (typeof requested !== 'string' || requested.trim().length === 0) {
        return ACCOUNTS;
    }

    const normalized = requested.trim().toLowerCase();
    const matches = ACCOUNTS.filter((account) => account.label.toLowerCase() === normalized);
    if (matches.length === 0) {
        businessOutcome(
            'unsupported_account_type',
            `This recipe only supports Savings and Checking accounts; "${requested}" is not one of them.`,
            { requested, supported: ACCOUNTS.map((account) => account.label) },
        );
    }
    return matches;
}

export async function runAction(
    context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown>; onHardFailure?: (info: { message: string; step?: string; expected?: string; observed?: string }, closeBrowser: () => Promise<void>) => Promise<void> } = {},
): Promise<RecipeOutcome> {
    const targetUrl = context.inputUrl && context.inputUrl.trim().length > 0 ? context.inputUrl : URL;
    const accounts = requestedAccounts(context.parameters);

    return runRecipe(async (page, out) => {
        await recipeGoto(page, targetUrl);
        await settle(page);
        await recipeClick(
            page,
            [
                { kind: 'role', role: 'button', name: 'GET STARTED NOW' },
                { kind: 'text', value: 'GET STARTED NOW' },
            ],
            'button "GET STARTED NOW"',
        );
        await settle(page);
        // Checkpoint: confirm the dashboard actually loaded before trusting
        // any balance we're about to read off it.
        await recipeCheckpoint(
            page,
            [
                { kind: 'text', value: 'Saving Account Activity' },
                { kind: 'text', value: 'Checking Account Activity' },
            ],
            'dashboard loaded after GET STARTED NOW',
        );

        for (const account of accounts) {
            out[account.outputKey] = (await extractBalance(page, account)).trim();
        }
    }, {
        headed: process.env.HEADED === '1',
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
        onHardFailure: context.onHardFailure,
    });
}
