import type { Step } from './browser.ts';

interface TaskParameters {
    accountScope?: 'savings' | 'checking' | 'all';
}

const BANK_BALANCE_ACTION = 'retrieve bank account balance details';

export function generateRecipe(
    url: string,
    task: string,
    allowedAction: string,
    parameters: TaskParameters,
    steps: Step[],
): string {
    if (normalizeAction(allowedAction) === normalizeAction(BANK_BALANCE_ACTION)) {
        return buildBankBalanceRecipe(url, task, allowedAction, parameters);
    }

    const body = steps.map(render).join('\n');
    return `// Generated by Discovery.ts -- do not edit by hand.
// Task: ${task}
// Action: ${allowedAction}
// Site: ${url}
// Recorded: ${new Date().toISOString()}

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../recipeRuntime.ts';

export const TASK = ${JSON.stringify(task)};
export const ACTION = ${JSON.stringify(allowedAction)};
export const URL = ${JSON.stringify(url)};

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown> } = {}): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
${body}
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters: context.parameters,
    });
}
`;
}

function buildBankBalanceRecipe(url: string, task: string, allowedAction: string, parameters: TaskParameters): string {
    return `// Generated by Discovery.ts -- do not edit by hand.
// Task: ${task}
// Action: ${allowedAction}
// Site: ${url}
// Recorded: ${new Date().toISOString()}

import { recipeClick, recipeExtract, recipeGoto, runRecipe, settle } from '../recipeRuntime.ts';
import type { Selector } from '../recipeRuntime.ts';

export const TASK = ${JSON.stringify(task)};
export const ACTION = ${JSON.stringify(allowedAction)};
export const URL = ${JSON.stringify(url)};

type AccountScope = 'savings' | 'checking' | 'all';

interface RecipeParameters {
    accountScope?: AccountScope;
    [key: string]: unknown;
}

interface AccountConfig {
    key: Exclude<AccountScope, 'all'>;
    label: string;
    anchors: string[];
    outputKey: string;
}

const ACCOUNTS: AccountConfig[] = [
    {
        key: 'savings',
        label: 'Savings',
        anchors: ['Saving Account Activity', 'Savings Account', 'SAVINGS'],
        outputKey: 'savings_balance',
    },
    {
        key: 'checking',
        label: 'Checking',
        anchors: ['Checking Account Activity', 'Checking Account', 'CHECKING'],
        outputKey: 'checking_balance',
    },
];

function resolveParameters(inputTask?: string, inputParameters?: RecipeParameters): RecipeParameters {
    const scope = inputParameters?.accountScope ?? inferAccountScope(inputTask ?? TASK);
    return { accountScope: scope };
}

function inferAccountScope(text: string): AccountScope {
    const normalized = text.toLowerCase();
    if (/(all|total|combined|sum|every account)/.test(normalized)) {
        return 'all';
    }
    if (/(check|checking|chequing|current)/.test(normalized)) {
        return 'checking';
    }
    return 'savings';
}

function balanceSelectors(account: AccountConfig): Selector[] {
    return account.anchors.flatMap((anchor) => [
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: '.balance' },
        { kind: 'within', anchorText: anchor, ancestor: 'mat-card', css: 'div' },
        { kind: 'within', anchorText: anchor, ancestor: 'div', css: '.balance' },
    ]);
}

function parseCurrency(value: string): number {
    return Number.parseFloat(value.replace(/[^0-9.-]/g, '')) || 0;
}

async function extractBalance(
    page: Parameters<typeof recipeGoto>[0],
    account: AccountConfig,
): Promise<string> {
    return recipeExtract(page, balanceSelectors(account), \`\${account.label} account balance\`);
}

export async function runAction(
    context: { recipePath?: string; inputTask?: string; inputUrl?: string; parameters?: Record<string, unknown> } = {},
): Promise<Record<string, string>> {
    const parameters = resolveParameters(context.inputTask, context.parameters as RecipeParameters | undefined);
    const targetUrl = context.inputUrl && context.inputUrl.trim().length > 0 ? context.inputUrl : URL;

    return runRecipe(async (page, out) => {
        await recipeGoto(page, targetUrl);
        await settle(page);
        await recipeClick(
            page,
            [
                { kind: 'role', role: 'button', name: 'GET STARTED NOW' },
                { kind: 'text', value: 'GET STARTED NOW' },
            ],
            'button "GET STARTED NOW"',
        );
        await settle(page);

        if (parameters.accountScope === 'all') {
            const balances: Record<string, string> = {};
            let total = 0;
            for (const account of ACCOUNTS) {
                const balance = (await extractBalance(page, account)).trim();
                balances[account.outputKey] = balance;
                total += parseCurrency(balance);
            }
            Object.assign(out, balances);
            out.account_scope = 'all';
            out.total_balance = total.toFixed(2);
            return;
        }

        const account = ACCOUNTS.find((item) => item.key === parameters.accountScope) ?? ACCOUNTS[0];
        const balance = (await extractBalance(page, account)).trim();
        out[account.outputKey] = balance;
        out.account_scope = account.key;
        out.account = account.label;
        out.balance = balance;
    }, {
        headed: process.env.HEADED === '1',
        recipe: context.recipePath,
        recipeTask: ACTION,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
        parameters,
    });
}
`;
}

function render(step: Step): string {
    const pad = '        ';
    switch (step.action) {
        case 'goto':
            return (
                `${pad}await recipeGoto(page, ${JSON.stringify(step.url)});\n` +
                `${pad}await settle(page);`
            );
        case 'click':
            return (
                `${pad}await recipeClick(page, ${json(step.selectors)}, ${JSON.stringify(step.description)});\n` +
                `${pad}await settle(page);`
            );
        case 'fill':
            return `${pad}await recipeFill(page, ${json(step.selectors)}, ${JSON.stringify(step.description)}, ${JSON.stringify(step.value)});`;
        case 'press':
            return `${pad}await recipePress(page, ${JSON.stringify(step.key)});\n${pad}await settle(page);`;
        case 'extract':
            return (
                `${pad}out[${JSON.stringify(step.name)}] = (await recipeExtract(page, ${json(step.selectors)}, ` +
                `${JSON.stringify(step.description)})).trim();`
            );
    }
}

function json(value: unknown): string {
    return JSON.stringify(value);
}

function normalizeAction(value: string): string {
    return value.toLowerCase().replace(/\s+/g, ' ').trim();
}
