import type { Step } from './browser.ts';

/**
 * Turn recorded steps into a recipe module.
 *
 * The model never writes this file. It drives the browser; we serialize what
 * actually worked. That is why the output is always valid TypeScript -- there
 * is no prose to strip and no fenced code block to parse out.
 */
export function generateRecipe(url: string, task: string, steps: Step[]): string {
    const body = steps.map(render).join('\n');

    return `// Generated by Discovery.ts -- do not edit by hand.
// Task: ${task}
// Site: ${url}
// Recorded: ${new Date().toISOString()}

import { recipeClick, recipeExtract, recipeFill, recipeGoto, recipePress, runRecipe, settle } from '../../recipeRuntime.ts';

export const TASK = ${JSON.stringify(task)};
export const URL = ${JSON.stringify(url)};

export async function runAction(context: { recipePath?: string; inputTask?: string; inputUrl?: string } = {}): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
${body}
    }, {
        headed: process.env.HEADED === "1",
        recipe: context.recipePath,
        recipeTask: TASK,
        recipeUrl: URL,
        inputTask: context.inputTask,
        inputUrl: context.inputUrl,
    });
}
`;
}

function render(step: Step): string {
    const pad = '        ';
    switch (step.action) {
        case 'goto':
            return (
                `${pad}await recipeGoto(page, ${JSON.stringify(step.url)});\n` +
                `${pad}await settle(page);`
            );
        case 'click':
            return (
                `${pad}await recipeClick(page, ${json(step.selectors)}, ${JSON.stringify(step.description)});\n` +
                `${pad}await settle(page);`
            );
        case 'fill':
            return `${pad}await recipeFill(page, ${json(step.selectors)}, ${JSON.stringify(step.description)}, ${JSON.stringify(step.value)});`;
        case 'press':
            return `${pad}await recipePress(page, ${JSON.stringify(step.key)});\n${pad}await settle(page);`;
        case 'extract':
            return (
                `${pad}out[${JSON.stringify(step.name)}] = (await recipeExtract(page, ${json(step.selectors)}, ` +
                `${JSON.stringify(step.description)})).trim();`
            );
    }
}

function json(value: unknown): string {
    return JSON.stringify(value);
}
