import type { Step } from './browser.ts';

/**
 * Turn recorded steps into a recipe module.
 *
 * The model never writes this file. It drives the browser; we serialize what
 * actually worked. That is why the output is always valid TypeScript -- there
 * is no prose to strip and no fenced code block to parse out.
 */
export function generateRecipe(url: string, task: string, steps: Step[]): string {
    const body = steps.map(render).join('\n');

    return `// Generated by Discovery.ts -- do not edit by hand.
// Task: ${task}
// Site: ${url}
// Recorded: ${new Date().toISOString()}

import { resolve, runRecipe, settle } from '../../recipeRuntime.ts';

export const TASK = ${JSON.stringify(task)};
export const URL = ${JSON.stringify(url)};

export async function runAction(): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
${body}
    }, { headed: process.env.HEADED === "1" });
}
`;
}

function render(step: Step): string {
    const pad = '        ';
    switch (step.action) {
        case 'goto':
            return (
                `${pad}await page.goto(${JSON.stringify(step.url)}, { waitUntil: 'domcontentloaded' });\n` +
                `${pad}await settle(page);`
            );
        case 'click':
            return (
                `${pad}await (await resolve(page, ${json(step.selectors)}, ${JSON.stringify(step.description)})).click();\n` +
                `${pad}await settle(page);`
            );
        case 'fill':
            return `${pad}await (await resolve(page, ${json(step.selectors)}, ${JSON.stringify(step.description)})).fill(${JSON.stringify(step.value)});`;
        case 'press':
            return `${pad}await page.keyboard.press(${JSON.stringify(step.key)});\n${pad}await settle(page);`;
        case 'extract':
            return (
                `${pad}out[${JSON.stringify(step.name)}] = (await (await resolve(page, ${json(step.selectors)}, ` +
                `${JSON.stringify(step.description)})).innerText()).trim();`
            );
    }
}

function json(value: unknown): string {
    return JSON.stringify(value);
}
