// Generated by Discovery.ts -- do not edit by hand.
// Task: tell me my saving account balance
// Site: https://www.ngpf.org/bank-sim/
// Recorded: 2026-09-17T19:45:44.015Z

import { runRecipe, settle } from '../../recipeRuntime.ts';

export const TASK = "tell me my saving account balance";
export const URL = "https://www.ngpf.org/bank-sim/";

export async function runAction(): Promise<Record<string, string>> {
    return runRecipe(async (page, out) => {
        await page.goto("https://www.ngpf.org/bank-sim/", { waitUntil: 'domcontentloaded' });
        await settle(page);
        await page.getByRole('button', { name: 'GET STARTED NOW' }).click();
        await settle(page);

        const savingsCard = page.locator('mat-card.home-cards', { hasText: 'Saving Account Activity' });
        out.savings_balance = (await savingsCard.locator('.balance').innerText()).trim();
    }, { headed: process.env.HEADED === "1" });
}
